version: "3.9"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docs:/usr/share/nginx/html